# Generated by Django 6.0.2 on 2026-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timestamp_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
